version: '3.3'

services:
  postgres:
    container_name: thou-postgres
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
  redis:
    container_name: thou-redis
    image: redis:7
    ports:
      - '6379:6379'
